version: '3.8'
volumes:
 flux_api_location_mongo:
services:
 mongodb:
  image: mongo:latest
  environment:
   MONGO_INITDB_ROOT_USERNAME: mongo
   MONGO_INITDB_ROOT_PASSWORD: mongo
   MONGO_INITDB_DATABASE: locationdb
  ports:
   - 27017:27017
  volumes:
   - flux_api_location_mongo:/data/db
   - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro