version: '3.8'
volumes:
 secure_flux_api:
services:
 mongodb:
  image: mongo:latest
  environment:
   MONGO_INITDB_ROOT_USERNAME: mongo
   MONGO_INITDB_ROOT_PASSWORD: mongo
   MONGO_INITDB_DATABASE: balancedb
  ports:
   - 27017:27017
  volumes:
   - secure_flux_api:/data/db
   - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro